### ISSUE TITLE
Introduction of Colossal-AI SysML

### ISSUE THREAD

**Issue by binmakeswell** [Jack47/hack-SysML#11]
Hi @Jack47 I noticed that you are very interested and experienced in SysML and create this interesting project.

Perhaps you would also be interested in [Colossal-AI](https://github.com/hpcaitech/ColossalAI). It's a unified deep learning system for the big model era, which integrates many efficient techniques like multi-dimensional tensor parallelism, sequence parallelism, heterogeneous memory management, etc.

By using Colossal-AI, we could help users to efficiently and quickly deploy large AI model training and inference, reducing large AI model budgets and scaling down the labor cost of learning and deployment.

Here are some [中文](https://mp.weixin.qq.com/s/7Z0M71-mO54CgBtqBeMv4A) and [English](https://medium.com/@hpcaitech/train-18-billion-parameter-gpt-models-with-a-single-gpu-on-your-personal-computer-8793d08332dc) blogs to help you know it.

Thank you for your review and look forward to your reply.

**Comment by Jack47** [comment]
cool, will spend sometime digging Colossal-AI's nearest features.
